### ISSUE TITLE
Executables installed by transitive dependencies are not globally symlinked

### ISSUE THREAD

**Issue by bilelomrani1** [pypa/pipx#1013]
I am using the Python application [SkyPilot](https://github.com/skypilot-org/skypilot) and chose to install it using `pipx` to isolate it from the rest of my dependencies. 

To reproduce, here is what I did:

- Switch to a Python 3.9 shell using `pyenv`
    ```bash
    pyenv shell 3.9
    ```
- Install SkyPilot in its own isolated environment using `pipx`, linking to the correct interpreter
    ```bash
    pipx install skypilot[gcp] --python $(which python)
    ```
- Make sure that SkyPilot is accessible globally and is connected (in my case to GCP)
    ```bash
    sky check
    ```
- Launch a test workload
    ```bash
    sky launch --cpus 1+ --memory 1+ --cloud gcp echo "Hello World"
    ```

SkyPilot then crashed with the following cryptic stacktrace

<details closed>
<summary>Stacktrace</summary>
<br>

```python
Traceback (most recent call last):
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/backend_utils.py", line 1355, in _query_head_ip_with_retries
    out = subprocess_utils.run(
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/subprocess_utils.py", line 30, in run
    return subprocess.run(cmd,
  File "/Users/bilelomrani/.pyenv/versions/3.9.17/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ray get-head-ip '/Users/bilelomrani/.sky/generated/sky-df91-bilelomrani.yml'' returned non-zero exit status 127.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/backend_utils.py", line 1424, in get_node_ips
    head_ip = _query_head_ip_with_retries(cluster_yaml,
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/backend_utils.py", line 1378, in _query_head_ip_with_retries
    raise RuntimeError('Failed to get head ip') from e
RuntimeError: Failed to get head ip

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bilelomrani/.local/bin/sky", line 8, in <module>
    sys.exit(cli())
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 239, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/cli.py", line 1109, in invoke
    return super().invoke(ctx)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/cli.py", line 1377, in launch
    _launch_with_confirm(task,
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/cli.py", line 793, in _launch_with_confirm
    sky.launch(
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/execution.py", line 487, in launch
    _execute(
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/execution.py", line 324, in _execute
    handle = backend.provision(task,
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 239, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/backend.py", line 56, in provision
    return self._provision(task, to_provision, dryrun, stream_logs,
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2502, in _provision
    ip_list = handle.external_ips(max_attempts=_FETCH_IP_MAX_ATTEMPTS,
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2213, in external_ips
    self._update_stable_cluster_ips(max_attempts=max_attempts)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/cloud_vm_ray_backend.py", line 2153, in _update_stable_cluster_ips
    cluster_external_ips = backend_utils.get_node_ips(
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/utils/common_utils.py", line 260, in _record
    return f(*args, **kwargs)
  File "/Users/bilelomrani/.local/pipx/venvs/skypilot/lib/python3.9/site-packages/sky/backends/backend_utils.py", line 1427, in get_node_ips
    raise exceptions.FetchIPError(
sky.exceptions.FetchIPError
```

</details>

After some investigations, I realized that
1. there was no error when I manually activate the venv created by `pipx`
2. the error is caused by the fact that `ray`, an executable installed by one of the `skypilot` dependencies, was not symlinked to `~/.local/bin` and thus (apparently) not accessible by `skypilot` at runtime.

I solved the problem by manually symlinking `ray` to `~/.local/bin`:

```
ln -s ~/.local/pipx/venvs/skypilot/bin/ray ~/.local/bin/ray
```

Is it something expected, can't we automatically detect the executables installed by transitive dependencies and symlink then properly to `~/.local/bin`?

**Comment by bilelomrani1** [comment]
I somehow missed it, but this is exactly the use case for `pipx inject --include-apps`, this solves my issue.
