### ISSUE TITLE
None of the possible ways to invoke `pipx run script.py` actually runs the script.

### ISSUE THREAD

**Issue by dangoodman** [pypa/pipx#1023]
**Describe the bug**
According to the [discussion](https://github.com/pypa/pipx/issues/913), `pipx run script.py` should run script.py after installing the mentioned requirements. However, it never happens in my case. 

**How to reproduce**

setup:
```
brew install pipx
pipx ensurepath

cat - > script.py <<'EOF'
#! /usr/bin/env -S pipx run
# Requirements:
#     ansicolors

from colors import bold

print(bold("Hello, world!".rjust(20, "-")))
EOF
```

1.
```
pipx run script.py
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 200, in run_pipx_command
    commands.run(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/run.py", line 104, in run
    venv.run_app(app, app_filename, app_args)
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 382, in run_app
    exec_app([str(self.bin_path / filename)] + app_args)
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/util.py", line 402, in exec_app
    os.execvpe(str(cmd[0]), [str(x) for x in cmd], env)
  File "<frozen os>", line 583, in execvpe
  File "<frozen os>", line 597, in _execvpe
OSError: [Errno 8] Exec format error: '/Users/dan/.local/pipx/.cache/87d83da4f83a45e/bin/script.py'
```

2.
```
pipx run ./script.py
ERROR: Invalid requirement: '/Users/dan/tmp/script.py'
Hint: It looks like a path. The path does exist.
Cannot determine package name from spec '/Users/dan/tmp/script.py'. Check package spec for errors.
```

3.
```
pipx run -- script.py
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 200, in run_pipx_command
    commands.run(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/run.py", line 104, in run
    venv.run_app(app, app_filename, app_args)
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 382, in run_app
    exec_app([str(self.bin_path / filename)] + app_args)
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/util.py", line 402, in exec_app
    os.execvpe(str(cmd[0]), [str(x) for x in cmd], env)
  File "<frozen os>", line 583, in execvpe
  File "<frozen os>", line 597, in _execvpe
OSError: [Errno 8] Exec format error: '/Users/dan/.local/pipx/.cache/87d83da4f83a45e/bin/script.py'
```

4.
```
pipx run -- ./script.py
ERROR: Invalid requirement: '/Users/dan/tmp/script.py'
Hint: It looks like a path. The path does exist.
Cannot determine package name from spec '/Users/dan/tmp/script.py'. Check package spec for errors.
```

5.
```
pipx run file:script.py
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'colors'
```

6.
```
mv script.py myscript.py

pipx run -- myscript.py
Fatal error from pip prevented installation. Full pip output in file:
    /Users/dan/.local/pipx/logs/cmd_2023-07-26_19.05.21_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement myscript-py (from versions: none)
    ERROR: No matching distribution found for myscript-py
Error installing myscript-py.
```

7.
```
pipx run -- ./myscript.py
⚠️  ./myscript.py is already on your PATH and installed at ./myscript.py. Downloading and running anyway.
ERROR: Invalid requirement: '/Users/dan/tmp/myscript.py'
Hint: It looks like a path. The path does exist.
Cannot determine package name from spec '/Users/dan/tmp/myscript.py'. Check package spec for errors.
```

**Expected behavior**
To output "Hello, world!" in bold.

Please let me know if I am doing something wrong.

**Comment by uranusjr** [comment]
The feature is not yet released if I remember correctly. Check the version and release notes more carefully please…

**Comment by dangoodman** [comment]
@uranusjr What is the status of the feature? Is it complete and waiting for the next release?
