### ISSUE TITLE
pipx fails to upgrade twitch-dl after python upgrades

### ISSUE THREAD

**Issue by superbonaci** [pypa/pipx#1080]
I had https://github.com/ihabunek/twitch-dl installed with pipx previously.
Then I upgraded brew.sh with:
```
$ brew update && brew upgrade
==> Upgrading 2 outdated packages:
python-certifi 2023.7.22 -> 2023.7.22_1
python-mutagen 1.47.0 -> 1.47.0_1
==> Pouring python-certifi--2023.7.22_1.arm64_sonoma.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink lib/python3.10/site-packages/certifi/__init__.py
Target /opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite python-certifi

To list all files that would be deleted:
  brew link --overwrite --dry-run python-certifi

Possible conflicting files are:
/opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py
/opt/homebrew/lib/python3.10/site-packages/certifi/__main__.py
/opt/homebrew/lib/python3.10/site-packages/certifi/cacert.pem
/opt/homebrew/lib/python3.10/site-packages/certifi/core.py
/opt/homebrew/lib/python3.10/site-packages/certifi/py.typed
==> Summary
🍺  /opt/homebrew/Cellar/python-certifi/2023.7.22_1: 43 files, 34.0KB
==> Running `brew cleanup python-certifi`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/python-certifi/2023.7.22... (34 files, 27.7KB)
==> Pouring python-mutagen--1.47.0_1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/python-mutagen/1.47.0_1: 218 files, 1.8MB
==> Running `brew cleanup python-mutagen`...
Removing: /opt/homebrew/Cellar/python-mutagen/1.47.0... (218 files, 1.8MB)
```
After it couldn't get `twitch-dl` to automatically upgrade:
```
$ pipx upgrade twitch-dl
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 247, in run_pipx_command
    return commands.upgrade(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/upgrade.py", line 162, in upgrade
    _ = _upgrade_venv(
        ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/upgrade.py", line 127, in _upgrade_venv
    versions_updated += _upgrade_package(
                        ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/upgrade.py", line 36, in _upgrade_package
    venv.upgrade_package(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 428, in upgrade_package
    pip_process = self._run_pip(
                  ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 447, in _run_pip
    return run_subprocess(cmd)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/util.py", line 176, in run_subprocess
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/.local/pipx/venvs/twitch-dl/bin/python'
```

So I had to uninstall and reinstall:
```
$ pipx uninstall twitch-dl
uninstalled twitch-dl! ✨ 🌟 ✨
```
```
$ pipx install twitch-dl
  installed package twitch-dl 2.1.3, installed using Python 3.11.6
  These apps are now globally available
    - twitch-dl
done! ✨ 🌟 ✨
```

**Comment by uranusjr** [comment]
This looks like a Homebrew problem, the `brew upgrade` call breaks all existing applications installed by pipx. I kind of have an idea why that happens (the upgrade also changed the underlying Python), but that can only be dealt by Homebrew, plus pipx maintainers do not maintain the Homebrew formula, so I think you need to ask for support in Homebrew instead.
