### ISSUE TITLE
`pipx reinstall-all` deleted everything

### ISSUE THREAD

**Issue by AstraLuma** [pypa/pipx#1110]
**Describe the bug**
Upgraded fedora, which apparently involved a system python upgrade, leading to this:

```
astraluma@nandi ~/code/unholy trunk @ poetry run unholy clone https://github.com/AstraLuma/unholy_test.git
Traceback (most recent call last):
  File "/home/astraluma/.local/bin/poetry", line 5, in <module>
    from poetry.console.application import main
ModuleNotFoundError: No module named 'poetry'
```

So I run `pipx reinstall-all` to have it recreate everything, and it just exploded and deleted everything.

```
astraluma@nandi ~/code/unholy trunk @ pipx reinstall-all
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled poetry! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing poetry.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled pipenv! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing pipenv.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled pyright! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing pyright.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled pip-tools! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing pip-tools.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled frogmouth! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing frogmouth.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled yt-dlp! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing yt-dlp.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled spotify-dl! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing spotify-dl.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled watchgha! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing watchgha.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled sphobjinv! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing sphobjinv.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled circup! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing circup.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled circpy! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing circpy from spec '/home/astraluma/code/circpy'.
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
/home/astraluma/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/usr/lib/python3.12/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/astraluma/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip
setuptools wheel' failed
uninstalled pipgrip! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /home/astraluma/.local/pipx/logs/cmd_2023-11-20_09.10.15_pip_errors.log

Error installing pipgrip.
The following package(s) failed to reinstall: poetry, pipenv, pyright, pip-tools, frogmouth, yt-dlp, spotify-dl,
watchgha, sphobjinv, circup, circpy, pipgrip
```

and now

```
astraluma@nandi ~/code/unholy trunk @ pipx list
nothing has been installed with pipx 😴
```

```
astraluma@nandi ~/.local/pipx @ ls *
logs:
cmd_2022-12-23_16.26.26_pip_errors.log  cmd_2023-10-18_15.45.19.log
cmd_2022-12-23_16.28.18_pip_errors.log  cmd_2023-10-18_15.48.03.log
cmd_2022-12-23_16.28.25_pip_errors.log  cmd_2023-10-18_15.48.06.log
cmd_2022-12-23_16.43.58_pip_errors.log  cmd_2023-10-20_12.40.56.log
cmd_2023-07-26_17.10.30_pip_errors.log  cmd_2023-11-20_09.10.15.log
cmd_2023-08-05_01.33.44.log             cmd_2023-11-20_09.10.15_pip_errors.log
cmd_2023-10-11_13.10.48.log             cmd_2023-11-20_09.10.54.log
cmd_2023-10-17_00.15.20.log             cmd_2023-11-20_09.14.22.log
cmd_2023-10-18_15.45.11.log

shared:
bin  include  lib  lib64  pyvenv.cfg

venvs:
```

Oh, and for completeness, the log is

```
PIP STDOUT
----------

PIP STDERR
----------
/home/astraluma/.local/pipx/venvs/pipgrip/bin/python: No module named pip
```

**How to reproduce**

Not sure there's an easy repro? I guess try some system upgrades.

**Expected behavior**

pipx reinstalling all my software. Or at least not deleting it.

**Comment by AstraLuma** [comment]
```
astraluma@nandi ~/code/unholy trunk @ pipx --version
1.2.1
```

Managed by dnf

**Comment by asyncon** [comment]
I had the same issue. The temporary fix is to trigger a recreation of the shared library's venv by removing the now incorrect python3 symlink that points to /usr/bin/python3

```bash
rm -f "${PIPX_SHARED_LIBS:-${PIPX_HOME:-$HOME/.local/pipx}/shared}/bin/python3"
```

pipx should now work.
