### ISSUE TITLE
pipx fails to install ytws because pip seemed to fail to build package: av==10.*

### ISSUE THREAD

**Issue by homocomputeris** [pypa/pipx#1165]
**Describe the bug**

pipx fails to install https://github.com/faker2048/youtube-faster-whisper on macos 14
However, pip itself installs it just fine:
```sh
$ test_venv/bin/python3 -m pip install ytws      
Collecting ytws
  Using cached ytws-0.4.2-py3-none-any.whl.metadata (6.4 kB)
Collecting click==8.1.6 (from ytws)
  Using cached click-8.1.6-py3-none-any.whl.metadata (3.0 kB)
Collecting faster-whisper==0.10.0 (from ytws)
  Using cached faster_whisper-0.10.0-py3-none-any.whl
Collecting loguru==0.7.0 (from ytws)
  Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting yt-dlp==2023.10.13 (from ytws)
  Using cached yt_dlp-2023.10.13-py2.py3-none-any.whl.metadata (158 kB)
Collecting av==10.* (from faster-whisper==0.10.0->ytws)
  Using cached av-10.0.0-cp311-cp311-macosx_10_9_x86_64.whl (26.0 MB)
Collecting ctranslate2<4,>=3.22 (from faster-whisper==0.10.0->ytws)
  Using cached ctranslate2-3.23.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (10 kB)
Collecting huggingface-hub>=0.13 (from faster-whisper==0.10.0->ytws)
  Using cached huggingface_hub-0.20.1-py3-none-any.whl.metadata (12 kB)
Collecting tokenizers<0.16,>=0.13 (from faster-whisper==0.10.0->ytws)
  Using cached tokenizers-0.15.0-cp311-cp311-macosx_10_7_x86_64.whl.metadata (6.7 kB)
Collecting onnxruntime<2,>=1.14 (from faster-whisper==0.10.0->ytws)
  Using cached onnxruntime-1.16.3-cp311-cp311-macosx_10_15_x86_64.whl.metadata (4.3 kB)
Collecting mutagen (from yt-dlp==2023.10.13->ytws)
  Downloading mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
Collecting pycryptodomex (from yt-dlp==2023.10.13->ytws)
  Using cached pycryptodomex-3.19.0-cp35-abi3-macosx_10_9_x86_64.whl.metadata (3.4 kB)
Collecting websockets (from yt-dlp==2023.10.13->ytws)
  Using cached websockets-12.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (6.6 kB)
Collecting certifi (from yt-dlp==2023.10.13->ytws)
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting brotli (from yt-dlp==2023.10.13->ytws)
  Using cached Brotli-1.1.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: setuptools in ./test_venv/lib/python3.11/site-packages (from ctranslate2<4,>=3.22->faster-whisper==0.10.0->ytws) (68.2.2)
Collecting numpy (from ctranslate2<4,>=3.22->faster-whisper==0.10.0->ytws)
  Using cached numpy-1.26.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting pyyaml<7,>=5.3 (from ctranslate2<4,>=3.22->faster-whisper==0.10.0->ytws)
  Downloading PyYAML-6.0.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting filelock (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Downloading filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached fsspec-2023.12.2-py3-none-any.whl.metadata (6.8 kB)
Collecting requests (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tqdm>=4.42.1 (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting packaging>=20.9 (from huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting coloredlogs (from onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting flatbuffers (from onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting protobuf (from onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached protobuf-4.25.1-cp37-abi3-macosx_10_9_universal2.whl.metadata (541 bytes)
Collecting sympy (from onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting charset-normalizer<4,>=2 (from requests->huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->huggingface-hub>=0.13->faster-whisper==0.10.0->ytws)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting mpmath>=0.19 (from sympy->onnxruntime<2,>=1.14->faster-whisper==0.10.0->ytws)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached ytws-0.4.2-py3-none-any.whl (8.6 kB)
Using cached click-8.1.6-py3-none-any.whl (97 kB)
Using cached yt_dlp-2023.10.13-py2.py3-none-any.whl (3.1 MB)
Using cached ctranslate2-3.23.0-cp311-cp311-macosx_10_9_x86_64.whl (14.6 MB)
Using cached huggingface_hub-0.20.1-py3-none-any.whl (330 kB)
Using cached onnxruntime-1.16.3-cp311-cp311-macosx_10_15_x86_64.whl (7.1 MB)
Using cached tokenizers-0.15.0-cp311-cp311-macosx_10_7_x86_64.whl (2.6 MB)
Using cached Brotli-1.1.0-cp311-cp311-macosx_10_9_x86_64.whl (446 kB)
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 844.7 kB/s eta 0:00:00
Downloading mutagen-1.47.0-py3-none-any.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 2.2 MB/s eta 0:00:00
Using cached pycryptodomex-3.19.0-cp35-abi3-macosx_10_9_x86_64.whl (1.6 MB)
Using cached websockets-12.0-cp311-cp311-macosx_10_9_x86_64.whl (121 kB)
Using cached fsspec-2023.12.2-py3-none-any.whl (168 kB)
Using cached numpy-1.26.2-cp311-cp311-macosx_10_9_x86_64.whl (20.6 MB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 1.4 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp311-cp311-macosx_10_9_x86_64.whl (187 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.9/187.9 kB 3.0 MB/s eta 0:00:00
Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Using cached protobuf-4.25.1-cp37-abi3-macosx_10_9_universal2.whl (394 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_10_9_x86_64.whl (121 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Installing collected packages: mpmath, flatbuffers, brotli, av, websockets, urllib3, typing-extensions, tqdm, sympy, pyyaml, pycryptodomex, protobuf, packaging, numpy, mutagen, loguru, idna, humanfriendly, fsspec, filelock, click, charset-normalizer, certifi, yt-dlp, requests, ctranslate2, coloredlogs, onnxruntime, huggingface-hub, tokenizers, faster-whisper, ytws
Successfully installed av-10.0.0 brotli-1.1.0 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.6 coloredlogs-15.0.1 ctranslate2-3.23.0 faster-whisper-0.10.0 filelock-3.13.1 flatbuffers-23.5.26 fsspec-2023.12.2 huggingface-hub-0.20.1 humanfriendly-10.0 idna-3.6 loguru-0.7.0 mpmath-1.3.0 mutagen-1.47.0 numpy-1.26.2 onnxruntime-1.16.3 packaging-23.2 protobuf-4.25.1 pycryptodomex-3.19.0 pyyaml-6.0.1 requests-2.31.0 sympy-1.12 tokenizers-0.15.0 tqdm-4.66.1 typing-extensions-4.9.0 urllib3-2.1.0 websockets-12.0 yt-dlp-2023.10.13 ytws-0.4.2

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python3 -m pip install --upgrade pip
test_venv/bin/python3 -m pip install ytws  20.54s user 4.71s system 85% cpu 29.696 total

$ ./test_venv/bin/ytws dt --help
Usage: ytws dt [OPTIONS]

  Download video/audio from Youtube and generate subtitles.

Options:
  -u, --url TEXT         Youtube URL.  [required]
  -n, --threads INTEGER  Number of threads to use.
  -f, --format TEXT      Download format. See: https://github.com/yt-dlp/yt-
                         dlp#format-selection-examples
  -t, --translate        Translate the subtitles to English.
  -m, --model_name TEXT  Name of the model to use. e.g.  (tiny, tiny.en, base,
                         base.en, small, small.en,          medium, medium.en,
                         large-v1, or large-v2 or large-v3), recommended:
                         (large-v3)
  -r, --model_root TEXT  Root directory for the models.
  --cpu                  Use CPU instead of GPU. This is useful if you do not
                         have a GPU.
  -s, --srt_only         Only generate subtitles. Do not download video.
  -v, --video_only       Only download video. Do not generate subtitles.
  --help                 Show this message and exit.
```

**How to reproduce**

1. `brew install pipx`
2. 
```shell
pipx install --verbose ytws                                      
pipx >(setup:824): pipx version is 1.3.3
pipx >(setup:825): Default python interpreter is '/usr/local/opt/python@3.12/libexec/bin/python'
pipx >(package_name_from_spec:370): Determined package name: ytws
pipx >(package_name_from_spec:371): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:171): running /usr/local/opt/python@3.12/libexec/bin/python -m venv --without-pip /Users/user/.local/pipx/venvs/ytws
pipx >(run_subprocess:171): running <checking pip's availability>
pipx >(run_subprocess:171): running /Users/user/.local/pipx/venvs/ytws/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:171): running /Users/user/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:171): running /Users/user/.local/pipx/venvs/ytws/bin/python --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: ytws
installing ytws...
pipx >(run_subprocess:171): running /Users/user/.local/pipx/venvs/ytws/bin/python -m pip --no-input install ytws
pipx >(subprocess_post_check_handle_pip_error:322): '/Users/user/.local/pipx/venvs/ytws/bin/python -m pip --no-input install ytws' failed
pipx >(subprocess_post_check_handle_pip_error:337): Fatal error from pip prevented installation. Full pip output in file:
    /Users/user/.local/pipx/logs/cmd_2023-12-23_22.27.01_pip_errors.log

pipx >(analyze_pip_output:301): pip seemed to fail to build package:
    av==10.*

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Cython.Compiler.Errors.CompileError: av/logging.pyx

pipx >(rmdir:55): removing directory /Users/user/.local/pipx/venvs/ytws
Error installing ytws.
```
Log:
```
PIP STDOUT
----------
Collecting ytws
  Using cached ytws-0.4.2-py3-none-any.whl.metadata (6.4 kB)
Collecting click==8.1.6 (from ytws)
  Using cached click-8.1.6-py3-none-any.whl.metadata (3.0 kB)
Collecting faster-whisper==0.10.0 (from ytws)
  Using cached faster-whisper-0.10.0.tar.gz (1.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting loguru==0.7.0 (from ytws)
  Using cached loguru-0.7.0-py3-none-any.whl (59 kB)
Collecting yt-dlp==2023.10.13 (from ytws)
  Using cached yt_dlp-2023.10.13-py2.py3-none-any.whl.metadata (158 kB)
Collecting av==10.* (from faster-whisper==0.10.0->ytws)
  Using cached av-10.0.0.tar.gz (2.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      Compiling av/plane.pyx because it changed.
      [1/1] Cythonizing av/plane.pyx
      Compiling av/dictionary.pyx because it changed.
      [1/1] Cythonizing av/dictionary.pyx
      Compiling av/stream.pyx because it changed.
      [1/1] Cythonizing av/stream.pyx
      Compiling av/option.pyx because it changed.
      [1/1] Cythonizing av/option.pyx
      Compiling av/enum.pyx because it changed.
      [1/1] Cythonizing av/enum.pyx
      Compiling av/bytesource.pyx because it changed.
      [1/1] Cythonizing av/bytesource.pyx
      Compiling av/buffer.pyx because it changed.
      [1/1] Cythonizing av/buffer.pyx
      Compiling av/packet.pyx because it changed.
      [1/1] Cythonizing av/packet.pyx
      Compiling av/error.pyx because it changed.
      [1/1] Cythonizing av/error.pyx
      Compiling av/_core.pyx because it changed.
      [1/1] Cythonizing av/_core.pyx
      Compiling av/format.pyx because it changed.
      [1/1] Cythonizing av/format.pyx
      performance hint: av/logging.pyx:232:5: Exception check on 'log_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare 'log_callback' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on 'log_callback' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef const char *log_context_name(void *ptr) nogil:
          cdef log_context *obj = <log_context*>ptr
          return obj.name
      
      cdef lib.AVClass log_class
      log_class.item_name = log_context_name
                            ^
      ------------------------------------------------------------
      
      av/logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'const char *(void *) except? NULL nogil'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      # Start the magic!
      # We allow the user to fully disable the logging system as it will not play
      # nicely with subinterpreters due to FFmpeg-created threads.
      if os.environ.get('PYAV_LOGGING') != 'off':
          lib.av_log_set_callback(log_callback)
                                  ^
      ------------------------------------------------------------
      
      av/logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *, va_list) except * nogil'.
      Compiling av/logging.pyx because it changed.
      [1/1] Cythonizing av/logging.pyx
      Traceback (most recent call last):
        File "/Users/user/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 157, in <module>
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/sj/h031z_cj1h717hcwc59d6b0w0000gn/T/pip-build-env-tn289kn9/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: av/logging.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Expected behavior**

Install ytws.

**Comment by uranusjr** [comment]
This is an issue from `av`. You will need to ask for assistance from its maintainers.

**Comment by dukecat0** [comment]
An additional note:

pipx is using the Python 3.12 from Homebrew: `/usr/local/opt/python@3.12/libexec/bin/python`

Your own venv is using Python 3.11.

Run the following command should solve the issue temporarily:
```
pipx install ytws --python python3.11
```

**Comment by homocomputeris** [comment]
> This is an issue from `av`. You will need to ask for assistance from its maintainers.

Obviously, the issue is non-existent when installed via pip.

> pipx is using the Python 3.12 from Homebrew:

Thanks for this solution!
