### ISSUE TITLE
No apps associated with package dbt-core

### ISSUE THREAD

**Issue by jaklan** [pypa/pipx#1269]
**Describe the bug**

Something really weird happens when I try to install `dbt-core` with `pipx` (tested with the latest `1.4.3` version):
- when I try to install the latest `dbt-core` - I get the `No apps associated` error
- when I try to install `dbt-core<1.7` - `dbt` app is installed correctly
- when I try to force install the latest `dbt-core` on top of the `dbt-core<1.7` - it's upgraded successfully...
- when I try to install the latest `dbt-core` as a dependency of `dbt-redshift` - it also works

**How to reproduce**

```
❯ pipx install "dbt-core"    

No apps associated with package dbt-core or its dependencies. If you are attempting to install a library, pipx
should not be used. Consider using pip or a similar tool instead.

❯ pipx install "dbt-core<1.7"
  installed package dbt-core 1.6.9, installed using Python 3.10.9
  These apps are now globally available
    - dbt
done! ✨ 🌟 ✨

❯ pipx install "dbt-core" --force
Installing to existing venv 'dbt-core'
  installed package dbt-core 1.7.8, installed using Python 3.10.9
  These apps are now globally available
    - dbt
done! ✨ 🌟 ✨

❯ pipx install dbt-redshift '--include-deps'             
  installed package dbt-redshift 1.7.3, installed using Python 3.10.9
  These apps are now globally available
    - dbt
    - jp.py
done! ✨ 🌟 ✨
```

**Expected behavior**

`dbt` app is installed correctly for `dbt-core>=1.7`.

**Comment by jaklan** [comment]
Entrypoint is configured properly for `dbt-core==1.7.8`:

```
    entry_points={
        "console_scripts": ["dbt = dbt.cli.main:cli"],
    },
```

https://github.com/dbt-labs/dbt-core/blob/v1.7.8/core/setup.py#L45-L47

**Comment by dukecat0** [comment]
The first command works on my local machine. Could you run `pipx install dbt-core --verbose` and post the output here?

**Comment by jaklan** [comment]
@dukecat0 sure, here it is:
```shell
❯ pipx install dbt-core --verbose
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/Users/<user>/.pyenv/versions/3.10.9/bin/python3'
pipx >(package_name_from_spec:370): Determined package name: dbt-core
pipx >(package_name_from_spec:371): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:168): running /Users/<user>/.pyenv/versions/3.10.9/bin/python3 -m venv --without-pip /Users/<user>/.local/pipx/venvs/dbt-core
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: dbt-core
installing dbt-core...
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python -m pip --no-input install dbt-core
pipx >(run_subprocess:168): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:339): get_venv_metadata_for_package: 414ms
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: dbt-core
pipx >(rmdir:55): removing directory /Users/<user>/.local/pipx/venvs/dbt-core

No apps associated with package dbt-core or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

**Comment by jaklan** [comment]
Also:
```shell
❯ pipx install dbt-core -vv
pipx >(setup:858): 2024-02-27 14:41:14
pipx >(setup:859): /opt/homebrew/bin/pipx install dbt-core -vv
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/Users/<user>/.pyenv/versions/3.10.9/bin/python3'
pipx >(package_name_from_spec:370): Determined package name: dbt-core
pipx >(package_name_from_spec:371): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:168): running /Users/<user>/.pyenv/versions/3.10.9/bin/python3 -m venv --without-pip /Users/<user>/.local/pipx/venvs/dbt-core
pipx >(run_subprocess:190): stdout:
pipx >(run_subprocess:192): stderr:
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:190): stdout: ModuleSpec(name='pip', loader=<_frozen_importlib_external.SourceFileLoader object at 0x1047706d0>, origin='/Users/<user>/.local/pipx/shared/lib/python3.10/site-packages/pip/__init__.py', submodule_search_locations=['/Users/<user>/.local/pipx/shared/lib/python3.10/site-packages/pip'])
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:190): stdout: /Users/<user>/.local/pipx/venvs/dbt-core/lib/python3.10/site-packages
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:190): stdout: /Users/<user>/.local/pipx/shared/lib/python3.10/site-packages
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python --version
pipx >(run_subprocess:190): stdout: Python 3.10.9
pipx >(run_subprocess:192): stderr:
pipx >(run_subprocess:193): returncode: 0
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: dbt-core
installing dbt-core...
pipx >(run_subprocess:168): running /Users/<user>/.local/pipx/venvs/dbt-core/bin/python -m pip --no-input install dbt-core
pipx >(run_subprocess:193): returncode: 0
pipx >(run_subprocess:168): running <fetch_info_in_venv commands>
pipx >(run_subprocess:190): stdout: {"sys_path": ["/Users/<user>/.pyenv/versions/3.10.9/lib/python310.zip", "/Users/<user>/.pyenv/versions/3.10.9/lib/python3.10", "/Users/<user>/.pyenv/versions/3.10.9/lib/python3.10/lib-dynload", "/Users/<user>/.local/pipx/venvs/dbt-core/lib/python3.10/site-packages", "/Users/<user>/.local/pipx/shared/lib/python3.10/site-packages"], "python_version": "3.10.9", "environment": {"implementation_name": "cpython", "implementation_version": "3.10.9", "os_name": "posix", "platform_machine": "arm64", "platform_release": "23.2.0", "platform_system": "Darwin", "platform_version": "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000", "python_full_version": "3.10.9", "platform_python_implementation": "CPython", "python_version": "3.10", "sys_platform": "darwin"}}
pipx >(run_subprocess:193): returncode: 0
pipx >(get_venv_metadata_for_package:339): get_venv_metadata_for_package: 334ms
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: dbt-core
pipx >(rmdir:55): removing directory /Users/<user>/.local/pipx/venvs/dbt-core

No apps associated with package dbt-core or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
pipx >(cli:924): PipxError: No apps associated with package dbt-core or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/commands/install.py", line 100, in install
    run_post_install_actions(
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/commands/common.py", line 410, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package dbt-core or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
pipx >(cli:932): pipx finished.
```

**Comment by jaklan** [comment]
@dukecat0 I have, partially, identified the issue - for some reason, in `pipx/shared` there were many more libraries than it should be, including `dbt`:
```shell
<user> in ~/.local/pipx/shared/lib/python3.10/site-packages via 🐍 v3.10.9 at 20:57:55
❯ ls
(...)
click
click-8.1.7.dist-info
colorama
colorama-0.4.6.dist-info
dateutil
dbt
dbt_core-1.7.5.dist-info
dbt_extractor
dbt_extractor-0.5.1.dist-info
dbt_semantic_interfaces
dbt_semantic_interfaces-0.4.3.dist-info
(...)
```

I have removed the directory and re-run `pipx install dbt-core` - the app was installed correctly then. I have also verified the new `pipx/shared` directory and it looks fine:

```shell
<user> in ~/.local/pipx/shared/lib/python3.10/site-packages via 🐍 v3.10.9 at 21:04:47
❯ ls
_distutils_hack             pkg_resources
distutils-precedence.pth    setuptools
pip                         setuptools-65.5.0.dist-info
pip-24.0.dist-info
```

I have no idea how these packages appeared in `pipx/shared`, but at least the problem is now solved 😉

**Comment by chrysle** [comment]
Closing for now, then, we can reopen if others experience this issue.

**Comment by Arcron-ArchLinux** [comment]
Well I use Arch and have the same issue when I try to install bs4 with pipx it gives the error given below
No apps associated with package bs4 or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.

**Comment by Gitznik** [comment]
> Well I use Arch and have the same issue when I try to install bs4 with pipx it gives the error given below `No apps associated with package bs4 or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.`

As far as I'm aware beautifulsoup does not have a CLI. What is your expected behavior here?

**Comment by Arcron-ArchLinux** [comment]
Well I know but I wanted to ask you how can I install it on my arch linux system I have tried using pip, pacman and pipx but it just does not work

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by Gitznik** [comment]
> Well I know but I wanted to ask you how can I install it on my arch linux system I have tried using pip, pacman and pipx but it just does not work
Pipx is for installing python applications, not packages. bs4 is a package. Please refer to their documentation on how to install it. Pipx is not the right tool for it.
