### ISSUE TITLE
pipx does not install pyproject.toml dependancies

### ISSUE THREAD

**Issue by GhostDog98** [pypa/pipx#1513]
**Describe the bug**

When installing a python package, pipx does not install dependancies as defined in the pyproject.toml

**How to reproduce**

git clone https://github.com/GhostDog98/lepus-neo
pipx install .
lepus
```
Traceback (most recent call last):
  File "/home/lilly/.local/bin/lepus", line 5, in <module>
    from lepus import main
  File "/home/lilly/.local/share/pipx/venvs/lepus/lib/python3.11/site-packages/lepus.py", line 5, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'
```
pipx inject lepus setuptools beautifulsoup4==4.9.3 dnspython==2.0.0 ipwhois==1.2.0 requests==2.25.1 shodan==1.25.0 slackclient==2.9.3 SQLAlchemy==1.4.18 termcolor==1.1.0 tqdm==4.61.1
lepus
 works fine now!

**Expected behavior**

It should have worked from just doing pipx install .

**Output of verbose**
```
└─$ pipx install -v .
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is '/usr/bin/python3.11'
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: /home/lilly/Lepus
pipx >(create_venv:162): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /usr/bin/python3.11 -m venv --without-pip /tmp/tmpckdmhn30
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(run_subprocess:175): running /tmp/tmpckdmhn30/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /home/lilly/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /tmp/tmpckdmhn30/bin/python --version
determining package name from '/home/lilly/Lepus'...
pipx >(run_subprocess:175): running /tmp/tmpckdmhn30/bin/python -m pip list --format=json
pipx >(run_subprocess:175): running /tmp/tmpckdmhn30/bin/python -m pip --no-input install --no-dependencies /home/lilly/Lepus
pipx >(run_subprocess:175): running /tmp/tmpckdmhn30/bin/python -m pip list --format=json
pipx >(install_package_no_deps:333): Determined package name: lepus
pipx >(package_name_from_spec:390): Package name determined in 15.4s
pipx >(create_venv:162): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /usr/bin/python3.11 -m venv --without-pip /home/lilly/.local/share/pipx/venvs/lepus
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(run_subprocess:175): running /home/lilly/.local/share/pipx/venvs/lepus/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /home/lilly/.local/share/pipx/venvs/lepus/bin/python --version
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: /home/lilly/Lepus
pipx >(install_package:245): Installing lepus from spec '/home/lilly/Lepus'
installing lepus from spec '/home/lilly/Lepus'...
pipx >(run_subprocess:175): running /home/lilly/.local/share/pipx/venvs/lepus/bin/python -m pip --no-input install /home/lilly/Lepus
pipx >(run_subprocess:175): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:349): get_venv_metadata_for_package: 66ms
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: /home/lilly/Lepus
  installed package lepus 1.0.0, installed using Python 3.11.8
  These apps are now globally available
    - lepus
done! ✨ 🌟 ✨
```

**Comment by GhostDog98** [comment]
Issue was between chair and keyboard 🤦‍♀️ .
I needed `dependencies = ["""]` in my [project] section instead
