### ISSUE TITLE
Package installed with pipx ends up invoking system-wide version installed with system package manager

### ISSUE THREAD

**Issue by piotr-dobrogost** [pypa/pipx#1557]
On Fedora 41 I have two system-wide pythons installed 3.13.0rc3 (default) and 3.12.7, mercurial and pipx:

```
[piotr@fedora]~% which python && python --version && which python3.12 && python3.12 --version 
/usr/bin/python
Python 3.13.0rc3
/usr/bin/python3.12
Python 3.12.7

[piotr@fedora]~% dnf5 list --installed pipx mercurial
Installed packages
mercurial.x86_64 6.8.1-2.fc41 <unknown>
pipx.noarch      1.7.1-1.fc41 fedora

```
As there are errors when running mercurial with the default python 3.13.0rc3 I thought I would install mercurial using pipx and instruct it to use python 3.12 instead:
```
[piotr@fedora]~% pipx install mercurial --python 3.12
⚠  Note: hg was already on your PATH at /usr/bin/hg
  installed package mercurial 6.8.1, installed using Python 3.12.7
  These apps are now globally available
    - hg
done! ✨ 🌟 ✨
```
However running `hg` somehow ends up invoking the system-wide binary at `/usr/bin/hg` ?!:
```
[piotr@fedora]~% which hg && hg --version
~/.local/bin/hg
Traceback (most recent call last):
  File "/usr/bin/hg", line 59, in <module>
    dispatch.run()
    ^^^^^^^^^^^^
  File "<frozen importlib.util>", line 209, in __getattribute__
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib64/python3.13/site-packages/mercurial/dispatch.py", line 20, in <module>
    from .i18n import _
  File "<frozen importlib.util>", line 209, in __getattribute__
  File "/usr/lib64/python3.13/site-packages/mercurial/i18n.py", line 14, in <module>
    from typing import (
        List,
    )
  File "<frozen importlib.util>", line 209, in __getattribute__
  File "/usr/lib64/python3.13/typing.py", line 2807, in <module>
    Hashable = _alias(collections.abc.Hashable, 0)  # Not generic.
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 214, in __getattribute__
ValueError: module object for 'collections.abc' substituted in sys.modules during a lazy load
```

The specific error is not relevant to the issue other than the fact it's the same error I got when running mercurial installed with the package manager and which made me try to see if it would work with stable version of python instead (by installing with pipx). ;)

**Comment by piotr-dobrogost** [comment]
The problem miraculously went away after a while…
