### ISSUE TITLE
FileNotFoundError When Calling `pipx list` with Empty Directory in Venv Directory 

### ISSUE THREAD

**Issue by kevinjfoley** [pypa/pipx#281]
**Describe the bug**

`pipx list` produces a `FileNotFoundError` when there is an empty or non pipx directory in `$PIPX_HOME/venvs`

**How to reproduce**

Create an empty dir in `$PIPX_HOME/venvs` and run `pipx list`.

<details>
  <summary>Output of `pipx list  --verbose`</summary>
  
```
venvs are in /Users/kfoley/.local/pipx/venvs
apps are exposed on your $PATH at /Users/kfoley/.local/bin
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/commands.py", line 576, in _get_package_summary
    metadata = venv.get_venv_metadata_for_package(package)
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/Venv.py", line 161, in get_venv_metadata_for_package
    self.python_path, VENV_METADATA_INSPECTOR, package, str(self.bin_path)
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/util.py", line 81, in get_script_output
    [str(interpreter), "-c", script, *args], stdout=subprocess.PIPE, env=env
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kfoley/.local/pipx/venvs/.cache/bin/python': '/Users/kfoley/.local/pipx/venvs/.cache/bin/python'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kfoley/.local/bin/pipx", line 10, in <module>
    sys.exit(cli())
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/main.py", line 547, in cli
    exit(run_pipx_command(parsed_pipx_args))
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/main.py", line 198, in run_pipx_command
    commands.list_packages(venv_container)
  File "/Users/kfoley/.local/pipx/venvs/pipx/lib/python3.7/site-packages/pipx/commands.py", line 639, in list_packages
    for package_summary in p.map(_get_package_summary, dirs):
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/kfoley/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kfoley/.local/pipx/venvs/.cache/bin/python': '/Users/kfoley/.local/pipx/venvs/.cache/bin/python'
```
</details>

**Expected behavior**

I think a warning that there was an issue with one of the `venv` directories or something along those lines would be more helpful.  I doubt many people have empty directories there, for me I had a `$PIPX_HOME/venvs/venvs` and a `$PIPX_HOME/venvs/.cache` directory which were causing the error.  They were both empty so I'm guessing I fat fingered into creation.

**Comment by meowmeowmeowcat** [comment]
Now it would display a warning:
```
$ pipx list
venvs are in /home/gitpod/.local/pipx/venvs
apps are exposed on your $PATH at /home/gitpod/.local/bin
   package black 22.6.0, installed using Python 3.8.13
    - black
    - blackd
⚠️  package non-exist has invalid interpreter /home/gitpod/.local/pipx/venvs/non-exist/bin/python
   package nox 2022.1.7, installed using Python 3.8.13
    - nox
    - tox-to-nox

One or more packages have a missing python interpreter.
    To fix, execute: pipx reinstall-all
```

**Comment by meowmeowmeowcat** [comment]
Closing it as fixed
