### ISSUE TITLE
install poetry with pipx fails : TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by butterflyx** [pypa/pipx#702]
**Describe the bug**
On a fresh install of ParrotOS 4.11 with python 3.9.2 installed, I get an error trying to install the poetry package with pipx.
I can reproduce the error and I can install poetry with the poetry manual installer, so I think this is on the pipx side

**How to reproduce**
```
pipx (run_pipx_command:125): Virtual Environment location is /home/jc/.local/pipx/venvs/poetry
pipx (_run:124): running /usr/bin/python3 -m venv /home/jc/.local/pipx/venvs/poetry
pipx (_run:124): running /home/jc/.local/pipx/venvs/poetry/bin/python -m pip install --upgrade pip
Requirement already satisfied: pip in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (21.1.2)
pipx (_run:124): running /home/jc/.local/pipx/venvs/poetry/bin/python -m pip install poetry
Requirement already satisfied: poetry in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (1.1.6)
Requirement already satisfied: cleo<0.9.0,>=0.8.1 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.8.1)
Requirement already satisfied: virtualenv<21.0.0,>=20.0.26 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (20.4.7)
Requirement already satisfied: tomlkit<1.0.0,>=0.7.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.7.2)
Requirement already satisfied: requests-toolbelt<0.10.0,>=0.9.1 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.9.1)
Requirement already satisfied: packaging<21.0,>=20.4 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (20.9)
Requirement already satisfied: shellingham<2.0,>=1.1 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (1.4.0)
Requirement already satisfied: cachecontrol[filecache]<0.13.0,>=0.12.4 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.12.6)
Requirement already satisfied: crashtest<0.4.0,>=0.3.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.3.1)
Requirement already satisfied: keyring<22.0.0,>=21.2.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (21.8.0)
Requirement already satisfied: cachy<0.4.0,>=0.3.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.3.0)
Requirement already satisfied: html5lib<2.0,>=1.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (1.1)
Requirement already satisfied: clikit<0.7.0,>=0.6.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (0.6.2)
Requirement already satisfied: pexpect<5.0.0,>=4.7.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (4.8.0)
Requirement already satisfied: requests<3.0,>=2.18 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (2.25.1)
Requirement already satisfied: pkginfo<2.0,>=1.4 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (1.7.0)
Requirement already satisfied: poetry-core<1.1.0,>=1.0.3 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from poetry) (1.0.3)
Requirement already satisfied: msgpack>=0.5.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry) (1.0.2)
Requirement already satisfied: lockfile>=0.9 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry) (0.12.2)
Requirement already satisfied: pylev<2.0,>=1.3 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from clikit<0.7.0,>=0.6.2->poetry) (1.4.0)
Requirement already satisfied: pastel<0.3.0,>=0.2.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from clikit<0.7.0,>=0.6.2->poetry) (0.2.1)
Requirement already satisfied: six>=1.9 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from html5lib<2.0,>=1.0->poetry) (1.16.0)
Requirement already satisfied: webencodings in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from html5lib<2.0,>=1.0->poetry) (0.5.1)
Requirement already satisfied: jeepney>=0.4.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from keyring<22.0.0,>=21.2.0->poetry) (0.6.0)
Requirement already satisfied: SecretStorage>=3.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from keyring<22.0.0,>=21.2.0->poetry) (3.3.1)
Requirement already satisfied: pyparsing>=2.0.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from packaging<21.0,>=20.4->poetry) (2.4.7)
Requirement already satisfied: ptyprocess>=0.5 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from pexpect<5.0.0,>=4.7.0->poetry) (0.7.0)
Requirement already satisfied: idna<3,>=2.5 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (1.26.5)
Requirement already satisfied: cryptography>=2.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from SecretStorage>=3.2->keyring<22.0.0,>=21.2.0->poetry) (3.4.7)
Requirement already satisfied: cffi>=1.12 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring<22.0.0,>=21.2.0->poetry) (1.14.5)
Requirement already satisfied: pycparser in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring<22.0.0,>=21.2.0->poetry) (2.20)
Requirement already satisfied: appdirs<2,>=1.4.3 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from virtualenv<21.0.0,>=20.0.26->poetry) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from virtualenv<21.0.0,>=20.0.26->poetry) (0.3.2)
Requirement already satisfied: filelock<4,>=3.0.0 in ./.local/pipx/venvs/poetry/lib/python3.9/site-packages (from virtualenv<21.0.0,>=20.0.26->poetry) (3.0.12)
Installing to existing directory '/home/jc/.local/pipx/venvs/poetry'
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
Same error message when installing the first time (no existing dir yet), Here used to reproduce error message.

**Expected behavior**
Able to install poetry with pipx

**Comment by uranusjr** [comment]
Python 3.9 removed `encoding` https://docs.python.org/3.9/library/json.html#json.loads

So we need to fix that.

**Comment by sir-sigurd** [comment]
Works for me:
```
$ pipx --version
0.16.3
$ pipx install poetry
  installed package poetry 1.1.6, Python 3.9.2
  These apps are now globally available
    - poetry
done! ✨ 🌟 ✨
```

@butterflyx have you tried to update pipx?

**Comment by uranusjr** [comment]
It seems like this has already been fixed. Your pipx version is too old and does not support 3.9. Given that the package is in `dist-packages`, you probably need to talk to ParrotOS maintainers to ask for a pipx upgrade.

**Comment by aidanmelen** [comment]
# Problem

I encountered the same error on a raspberrypi doing the following

```bash
$ apt-get install pipx -y
...

$ pipx ensurepath
...

$ python --version
Python 3.9.2

$ pipx --version
0.12.3.1

$ pipx install black
...
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

note that the apt-get package for`pipx` is out of date.

# Solution

Now with the [recommend installation method for linux](https://pypa.github.io/pipx/)

```bash
$ python3 -m pip install --user pipx
...

$ python3 -m pipx ensurepath
...

$ python3 -m pipx --version
1.0.0

$ $ python3 -m pipx install black
  installed package black 21.12b0, installed using Python 3.9.2
  These apps are now globally available
    - black
    - black-primer
    - blackd
⚠️  Note: '/home/pi/.local/bin' is not on your PATH environment variable. These apps will not be
    globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it,
    or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
```
