### ISSUE TITLE
Ubuntu 18.04 + Python 3.6 + Source: ModuleNotFoundError: No module named 'pipx'

### ISSUE THREAD

**Issue by hswong3i** [pypa/pipx#731]
**Describe the bug**

When installing pipx from source on Ubuntu 18.04 + Python 3.6, coming with following error message:
```
ModuleNotFoundError: No module named 'pipx'
```

**How to reproduce**

(FAILED) Running source build inside a Ubuntu 18.04 docker container with podman:

```bash
$ git clone https://github.com/pypa/pipx.git /tmp/pipx
$ cd /tmp/pipx/
$ sudo podman run -ti --rm --name ubuntu --hostname ubuntu -v $PWD:/workdir -w /workdir ubuntu:18.04 bash

root@ubuntu:/workdir# apt update && apt -y full-upgrade

root@ubuntu:/workdir# apt -y install python3-dev python3-pip python3-setuptools python3-wheel

root@ubuntu:/workdir# python3 --version
Python 3.6.9

root@ubuntu:/workdir# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

root@ubuntu:/workdir# pip3 install --system .
Processing /workdir
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-gm_x57a2-build/setup.py", line 14, in <module>
        setup()
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'pipx'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-gm_x57a2-build/
```
**Expected behavior**

(OK) Running binary build inside a Ubuntu 18.04 docker container with podman:

```bash
$ git clone https://github.com/pypa/pipx.git /tmp/pipx
$ cd /tmp/pipx/
$ sudo podman run -ti --rm --name ubuntu --hostname ubuntu -v $PWD:/workdir -w /workdir ubuntu:18.04 bash

root@ubuntu:/workdir# apt update && apt -y full-upgrade

root@ubuntu:/workdir# apt -y install python3-dev python3-pip python3-setuptools python3-wheel

root@ubuntu:/workdir# python3 --version
Python 3.6.9

root@ubuntu:/workdir# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

root@ubuntu:/workdir# pip3 install --system pipx
Collecting pipx
  Downloading https://files.pythonhosted.org/packages/d7/f5/fcdd69d2c4dbcac506e9751f71c28063acf1b82cca2a79a3e27da57ae724/pipx-0.16.4-py3-none-any.whl (53kB)
    100% |################################| 61kB 733kB/s 
Collecting packaging>=20.0 (from pipx)
  Downloading https://files.pythonhosted.org/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl (40kB)
    100% |################################| 40kB 1.9MB/s 
Collecting userpath>=1.6.0 (from pipx)
  Downloading https://files.pythonhosted.org/packages/78/26/50fe9e5003ccd28bba6dcca47dabf43470292ce9199f42f0c4c5d354cffa/userpath-1.7.0-py2.py3-none-any.whl
Collecting argcomplete<2.0,>=1.9.4 (from pipx)
  Downloading https://files.pythonhosted.org/packages/b7/9e/9dc74d330c07866d72f62d553fe8bdbe32786ff247a14e68b5659963e6bd/argcomplete-1.12.3-py2.py3-none-any.whl
Collecting importlib-metadata>=3.3.0; python_version < "3.8" (from pipx)
  Downloading https://files.pythonhosted.org/packages/71/c2/cb1855f0b2a0ae9ccc9b69f150a7aebd4a8d815bd951e74621c4154c52a8/importlib_metadata-4.8.1-py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=20.0->pipx)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |################################| 71kB 1.3MB/s 
Collecting click (from userpath>=1.6.0->pipx)
  Downloading https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl (97kB)
    100% |################################| 102kB 1.1MB/s 
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata>=3.3.0; python_version < "3.8"->pipx)
  Downloading https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=3.3.0; python_version < "3.8"->pipx)
  Downloading https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Installing collected packages: pyparsing, packaging, typing-extensions, zipp, importlib-metadata, click, userpath, argcomplete, pipx
Successfully installed argcomplete-1.12.3 click-8.0.1 importlib-metadata-4.8.1 packaging-21.0 pipx-0.16.4 pyparsing-2.4.7 typing-extensions-3.10.0.2 userpath-1.7.0 zipp-3.5.0

root@ubuntu:/workdir# pipx --version
0.16.4
```

(OK) Running source build inside a Ubuntu 20.04 docker container with podman:

```bash
$ git clone https://github.com/pypa/pipx.git /tmp/pipx
$ cd /tmp/pipx/
$ sudo podman run -ti --rm --name ubuntu --hostname ubuntu -v $PWD:/workdir -w /workdir ubuntu:20.04 bash

root@ubuntu:/workdir# apt update && apt -y full-upgrade

root@ubuntu:/workdir# apt -y install python3-dev python3-pip python3-setuptools python3-wheel

root@ubuntu:/workdir# python3 --version
Python 3.8.10

root@ubuntu:/workdir# pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

root@ubuntu:/workdir# pip3 install --system .
Processing /workdir
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting userpath>=1.6.0
  Downloading userpath-1.7.0-py2.py3-none-any.whl (14 kB)
Collecting argcomplete<2.0,>=1.9.4
  Downloading argcomplete-1.12.3-py2.py3-none-any.whl (38 kB)
Collecting packaging>=20.0
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 30.8 MB/s 
Collecting click
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 34.2 MB/s 
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 31.6 MB/s 
Building wheels for collected packages: pipx
  Building wheel for pipx (PEP 517) ... done
  Created wheel for pipx: filename=pipx-0.16.4.1.dev0-py3-none-any.whl size=53434 sha256=fa9d3db464252d37774947f3c6eef1f608e51761058a7de3f91b3228e250fd76
  Stored in directory: /tmp/pip-ephem-wheel-cache-pppbxsgj/wheels/f9/50/9a/27a41de1d5b92a2511009e8a41bffb22bcbb226dcf1d45561b
Successfully built pipx
Installing collected packages: click, userpath, argcomplete, pyparsing, packaging, pipx
Successfully installed argcomplete-1.12.3 click-8.0.1 packaging-21.0 pipx-0.16.4.1.dev0 pyparsing-2.4.7 userpath-1.7.0

root@ubuntu:/workdir# pipx --version
0.16.4.1.dev0
```

**Comment by uranusjr** [comment]
This is related to your setuptools and pip versions. Ubuntu 18.04 ships ancient versions of those packages that do not support installing pipx (pip 9.0.1 was released in 2016).

**Comment by hswong3i** [comment]
I am now packaging setuptools and related as https://build.opensuse.org/package/show/home:alvistack/pypa-setuptools-58.2.0

Now pipx could get the latest required dependencies. Thank you very much.
