### ISSUE TITLE
pipx reinstall-all raises AttributeError

### ISSUE THREAD

**Issue by tactlessfish** [pypa/pipx#776]
**Describe the bug**
When I run `pipx reinstall-all`, I get the following output:
```
Traceback (most recent call last):
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/bin/.pipx-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/main.py", line 767, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/main.py", line 247, in run_pipx_command
    return commands.reinstall_all(
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 106, in reinstall_all
    package_exit = reinstall(
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 30, in reinstall
    if Path(python).is_relative_to(venv_dir):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'
```
Interestingly enough, manually reinstalling packages works just fine.

**How to reproduce**
- Platform: M1 Macbook, MacOS 11.6 (20G165)
- pipx 0.16.4.1.dev0 installed with nix home-manager

Run `pipx reinstall-all`.

Output with `--verbose` flag:
```
pipx >(setup:717): pipx version is 0.16.4.1.dev0
pipx >(setup:718): Default python interpreter is '/nix/store/5rpfiqanhg1gi1a8k4qq69mxbhz3nxnq-python3-3.8.12/bin/python3.8'
pipx >(upgrade:91): Upgrading shared libraries in /Users/fisher/.local/pipx/shared
upgrading shared libraries...
pipx >(run_subprocess:173): running /Users/fisher/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install --upgrade pip setuptools wheel
Traceback (most recent call last):
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/bin/.pipx-wrapped", line 9, in <module>
    sys.exit(cli())
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/main.py", line 767, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/main.py", line 247, in run_pipx_command
    return commands.reinstall_all(
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 106, in reinstall_all
    package_exit = reinstall(
  File "/nix/store/bzqvvmgm3xj9433339sz1hgxg93g1g1f-python3.8-pipx-0.16.5/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 30, in reinstall
    if Path(python).is_relative_to(venv_dir):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'
```

**Comment by rkhwaja** [comment]
I think this was fixed by https://github.com/pypa/pipx/pull/756 and so fixed by the 0.16.5 release
