### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by varac** [pypa/pipx#821]
**Describe the bug**

I am unable to install most packages I had installed before with pipx after removing `~/.local/pipx/` (i.e. `fints2ledger`), pipx fails with `TypeError: slice indices must be integers or None or have an __index__ method`.
Some packages *do* install just fine (i.e. `rstcheck`).
pipx is installed as ubuntu package (PopOS 21.10).

**How to reproduce**

```
❯ rm -rf ~/.local/pipx/

❯ pipx --version
1.0.0

❯ pipx list
nothing has been installed with pipx 😴

❯ pipx install --verbose fints2ledger
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/usr/bin/python3'
pipx >(package_name_from_spec:323): Determined package name: fints2ledger
pipx >(package_name_from_spec:324): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:172): running /usr/bin/python3 -m venv --without-pip /home/varac/.local/pipx/venvs/fints2ledger
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/fints2ledger/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/varac/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/fints2ledger/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: fints2ledger
installing fints2ledger...
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/fints2ledger/bin/python -m pip install fints2ledger
pipx >(run_subprocess:172): running <fetch_info_in_venv commands>

pipx >(rmdir:55): removing directory /home/varac/.local/pipx/venvs/fints2ledger
Traceback (most recent call last):
  File "/usr/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 779, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 60, in install
    venv.install_package(
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 244, in install_package
    self._update_package_metadata(
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 318, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 300, in get_venv_metadata_for_package
    venv_metadata = inspect_venv(
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 251, in inspect_venv
    app_paths_of_dependencies = _dfs_package_apps(
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 142, in _dfs_package_apps
    app_paths_of_dependencies = _dfs_package_apps(
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 121, in _dfs_package_apps
    dependencies = get_package_dependencies(
  File "/usr/lib/python3/dist-packages/pipx/venv_inspect.py", line 54, in get_package_dependencies
    for req in map(Requirement, dist.requires or []):
  File "/home/varac/.local/lib/python3.9/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 1100, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 4024, in parseImpl
    return e._parse(
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 4854, in parseImpl
    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 827, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/home/varac/.local/lib/python3.9/site-packages/pyparsing/core.py", line 283, in wrapper
    ret = func(*args[limit:])
  File "/home/varac/.local/lib/python3.9/site-packages/packaging/requirements.py", line 71, in <lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method

❯ pipx install --verbose rstcheck    
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/usr/bin/python3'
pipx >(package_name_from_spec:323): Determined package name: rstcheck
pipx >(package_name_from_spec:324): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:172): running /usr/bin/python3 -m venv --without-pip /home/varac/.local/pipx/venvs/rstcheck
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/rstcheck/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/varac/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/rstcheck/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: rstcheck
installing rstcheck...
pipx >(run_subprocess:172): running /home/varac/.local/pipx/venvs/rstcheck/bin/python -m pip install rstcheck
pipx >(run_subprocess:172): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:303): get_venv_metadata_for_package: 36ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: rstcheck
pipx >(_symlink_package_apps:124): Same path /home/varac/.local/bin/rstcheck and /home/varac/.local/pipx/venvs/rstcheck/bin/rstcheck
pipx >(needs_upgrade:69): Time since last upgrade of shared libs, in seconds: 36. Upgrade will be run by pipx if greater than 2592000.
  installed package rstcheck 3.3.1, installed using Python 3.9.7
  These apps are now globally available
    - rstcheck
done! ✨ 🌟 ✨
```

**Expected behavior**

Package should get installed without an error.

**Comment by CaptainJawZ** [comment]
having this same issue, started a day or two ago.

**Comment by wlritchi** [comment]
This looks a heck of a lot like pyparsing/pyparsing#329. Are you using Arch Linux or a derivative? It [recently updated pyparsing through 3.0.5](https://github.com/archlinux/svntogit-packages/commits/packages/python-pyparsing/trunk) (as of ~15 hours ago) but a fresh update should solve it (as of ~4 hours ago).

**Comment by varac** [comment]
Unfortunately, I'm not on Arch, but on PopOS 21.10 (based on Ubuntu), and using a distribuion deb package.
Would releasing a new version and afterwards installing via brew/pip help ?

**Comment by wlritchi** [comment]
> Unfortunately, I'm not on Arch, but on PopOS 21.10 (based on Ubuntu), and using a distribuion deb package. Would releasing a new version and afterwards installing via brew/pip help ?

I believe you can check the version of pyparsing you have with `pip list | grep pyparsing`. Version 3.0.5 changed some internal details that [pypa/packaging](https://github.com/pypa/packaging) was relying on, 3.0.6 reverted those changes.

If you're not on 3.0.5, it's probably a different issue. But if you *are* on 3.0.5, there's your diagnosis, and the fix is to install 3.0.6+ and let the distro maintainer know about the issue :)

**Comment by CaptainJawZ** [comment]
> Unfortunately, I'm not on Arch, but on PopOS 21.10 (based on Ubuntu), and using a distribuion deb package. Would releasing a new version and afterwards installing via brew/pip help ?

That was it for me! it's on pyparsing 3.0.7 now and it works again.

**Comment by meowmeowmeowcat** [comment]
I am closing this since there's nothing we can fix here.
