### ISSUE TITLE
Unable to Install Package Using Python 3.6

### ISSUE THREAD

**Issue by jplindquist** [pypa/pipx#841]
**Describe the bug**
I am unable to install a package using pipx installed through Homebrew (MacOS), and Python 3.6 (installed using pyenv), receiving the following error (full trace below along with steps to duplicate and additional outputs).
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**How to reproduce**
```
pipx install git+https://github.com/azweb76/x-crypto --python $(which python3.6) --verbose
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/usr/local/Cellar/pipx/1.0.0/libexec/bin/python3.10'
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: git+https://github.com/azweb76/x-crypto
creating virtual environment...
pipx >(run_subprocess:172): running /Users/jplindquist/.pyenv/shims/python3.6 -m venv --without-pip /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpmpvfn3ly
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpmpvfn3ly/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /Users/jplindquist/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpmpvfn3ly/bin/python --version
determining package name from 'git+https://github.com/azweb76/x-crypto'...
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpmpvfn3ly/bin/python -m pip list --format=json
Traceback (most recent call last):
  File "/usr/local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/main.py", line 779, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/commands/install.py", line 30, in install
    package_name = package_name_from_spec(
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/commands/common.py", line 333, in package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/venv.py", line 268, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/usr/local/Cellar/pipx/1.0.0/libexec/lib/python3.10/site-packages/pipx/venv.py", line 348, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Further debugging somehow shows that pip is not available in the venv

```
❯ /Users/jplindquist/.pyenv/shims/python3.6 -m venv --without-pip /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb
jplindquist in ~/dev
❯ /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python -c "import sysconfig; print(sysconfig.get_path('purelib'))"
/var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/lib/python3.6/site-packages
jplindquist in ~/dev
❯ /Users/jplindquist/.local/pipx/shared/bin/python -c "import sysconfig; print(sysconfig.get_path('purelib'))"
/Users/jplindquist/.local/pipx/shared/lib/python3.9/site-packages
jplindquist in ~/dev
❯ /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python --version
Python 3.6.15
jplindquist in ~/dev
❯ /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python -m pip list --format=json
/var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python: No module named pip
```

**Expected behavior**
Temporarily modified local source [here](https://github.com/pypa/pipx/blob/1.0.0/src/pipx/venv.py#L161) to remove `--without-pip` and reran install successfully, and also tested with a subcommand run prior to the list command

```
❯ /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python -m ensurepip
Looking in links: /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpvy64qf0x
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-18.1 setuptools-40.6.2
jplindquist in ~/dev
❯ /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpplzj70mb/bin/python -m pip list --format=json
[{"name": "pip", "version": "18.1"}, {"name": "setuptools", "version": "40.6.2"}]
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
pipx install git+https://github.com/azweb76/x-crypto --python $(which python3.6) --verbose
pipx >(setup:729): pipx version is 1.0.0
pipx >(setup:730): Default python interpreter is '/usr/local/Cellar/pipx/1.0.0/libexec/bin/python3.10'
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: git+https://github.com/azweb76/x-crypto
creating virtual environment...
pipx >(run_subprocess:172): running /Users/jplindquist/.pyenv/shims/python3.6 -m venv /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /Users/jplindquist/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5/bin/python --version
determining package name from 'git+https://github.com/azweb76/x-crypto'...
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5/bin/python -m pip list --format=json
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5/bin/python -m pip install --no-dependencies git+https://github.com/azweb76/x-crypto
pipx >(run_subprocess:172): running /var/folders/fw/ywkh_s8j3q13cplp0tnx7x_dvlvk_1/T/tmpq1qc88z5/bin/python -m pip list --format=json
pipx >(install_package_no_deps:284): Determined package name: xcrypto
pipx >(package_name_from_spec:337): Package name determined in 9.1s
creating virtual environment...
pipx >(run_subprocess:172): running /Users/jplindquist/.pyenv/shims/python3.6 -m venv /Users/jplindquist/.local/pipx/venvs/xcrypto
pipx >(run_subprocess:172): running /Users/jplindquist/.local/pipx/venvs/xcrypto/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:172): running /Users/jplindquist/.local/pipx/venvs/xcrypto/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: git+https://github.com/azweb76/x-crypto
installing xcrypto from spec 'git+https://github.com/azweb76/x-crypto'...
pipx >(run_subprocess:172): running /Users/jplindquist/.local/pipx/venvs/xcrypto/bin/python -m pip install git+https://github.com/azweb76/x-crypto
pipx >(run_subprocess:172): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:304): get_venv_metadata_for_package: 153ms
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: git+https://github.com/azweb76/x-crypto
pipx >(_symlink_package_apps:148): ⚠️  Note: xcrypto was already on your PATH at /Users/jplindquist/.pyenv/shims/xcrypto
pipx >(needs_upgrade:69): Time since last upgrade of shared libs, in seconds: 1784. Upgrade will be run by pipx if greater than 2592000.
  installed package xcrypto 1.3.1, installed using Python 3.6.15
  These apps are now globally available
    - xcrypto
```

Is there another / better way to get this working, or anything else that I may have missed?  The package in question relies on some older functionality in the cryptography library with Python 3.6.

**Comment by ssbarnea** [comment]
Sorry but py36 is EOL, so I really doubt it worth our time.

**Comment by jplindquist** [comment]
I was able to work around it anyway

**Comment by ZzZombo** [comment]
I have the same problem with a fresh installation of Python 3.11.2.

**Comment by ZzZombo** [comment]
Disregard that, it appears it failed because I didn't properly restart the terminal after `pipx` installation.
