### ISSUE TITLE
pipx fails to install application

### ISSUE THREAD

**Issue by P403n1x87** [pypa/pipx#850]
**Describe the bug**
When I try to install something with pipx 1.1.0 (e.g. `pipx install cog`) I get the following error log

~~~
PIP STDOUT
----------
Collecting cog
  Using cached cog-0.0.3.tar.gz (10 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jeqlweua/cog_8a1ecad07ff84b4091af1ad2a5c3aa03/setup.py", line 2, in <module>
          setup()
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/dist.py", line 462, in __init__
          _Distribution.__init__(
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/dist.py", line 885, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/home/gabriele/.local/pipx/shared/lib/python3.8/site-packages/setuptools/dist.py", line 884, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~~~

**How to reproduce**

~~~
❯ pipx install --verbose cog
pipx >(setup:757): pipx version is 1.1.0
pipx >(setup:758): Default python interpreter is '/usr/bin/python3.10'
pipx >(package_name_from_spec:323): Determined package name: cog
pipx >(package_name_from_spec:324): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:173): running /usr/bin/python3.10 -m venv --without-pip /home/gabriele/.local/pipx/venvs/cog
pipx >(run_subprocess:173): running /home/gabriele/.local/pipx/venvs/cog/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/gabriele/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:173): running /home/gabriele/.local/pipx/venvs/cog/bin/python --version
pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: cog
installing cog...
pipx >(run_subprocess:173): running /home/gabriele/.local/pipx/venvs/cog/bin/python -m pip install cog
pipx >(subprocess_post_check_handle_pip_error:335): '/home/gabriele/.local/pipx/venvs/cog/bin/python -m pip install cog' failed
pipx >(subprocess_post_check_handle_pip_error:352): Fatal error from pip prevented installation. Full pip output in file:
    /home/gabriele/.local/pipx/logs/cmd_2022-06-10_15.47.22_pip_errors.log

pipx >(analyze_pip_output:310): pip seemed to fail to build package:
    cog

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    error: metadata-generation-failed

pipx >(rmdir:55): removing directory /home/gabriele/.local/pipx/venvs/cog
Error installing cog.
~~~

**Expected behavior**

**Comment by P403n1x87** [comment]
Nevermind, I believe this is a problem with the `cog` package, and with someone not reading the docs :facepalm: 

> Cog is installed in the usual way, except the name is “cogapp”, not “cog”:
