### ISSUE TITLE
Linux install doesn't work out of the box with Python 3.10

### ISSUE THREAD

**Issue by dimaqq** [pypa/pipx#873]
Python3.10 install doesn't seem to work:

```command
> python3.10 -m pip install --user pipx

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)
```

Meanwhile Python3.9 works:

```command
> python3.9 -m pip install --user pipx

Collecting pipx
  Downloading pipx-1.1.0-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 2.4 MB/s 
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from pipx) (20.3)
Collecting argcomplete>=1.9.4
  Downloading argcomplete-2.0.0-py2.py3-none-any.whl (37 kB)
Collecting userpath>=1.6.0
  Downloading userpath-1.8.0-py3-none-any.whl (9.0 kB)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from userpath>=1.6.0->pipx) (7.0)
Installing collected packages: argcomplete, userpath, pipx
Successfully installed argcomplete-2.0.0 pipx-1.1.0 userpath-1.8.0
```

I've excluded the chance that pip or python is broken by installing `httpx[cli]` with 3.10 and that worked.

Versions tried:
```command
> python3.9 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.9)
> python3.10 -m pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

> python3.9 --version
Python 3.9.13
> python3.10 --version
Python 3.10.5
```

**Comment by uranusjr** [comment]
Looks like you just have a broken pip installed against 3.10. Since that package comes from `dist-packages`, you should report this to your Linux distribution provider, e.g. Debian or Ubuntu.

**Comment by dimaqq** [comment]
Confirming that I can install `pipx` using the recommended command in a Docker container.
Must be something odd in my host environment.
