### ISSUE TITLE
Pipx install does not honour --index-url when it updates pip/setuptools/wheel

### ISSUE THREAD

**Issue by martibutler** [pypa/pipx#964]
**Describe the bug**
Pipx install does not honour --index-url when it updates pip/setuptools/wheel.

I am calling `pipx install` with an `--index-url <replace_with_artifactory _url>` and `--pip-args "--index-url <replace_with_artifactory _url>"` which correctly installs the given package using the correct index url.  

However when I use pipx install with `--verbose` I can see that underneath the hood there is a call to the following, which does not pass through the `--index-url`:
`python -m pip --disable-pip-version-check install --force-reinstall --upgrade pip setuptools wheel` 

Are there any config settings that I can fix this with OR can I stop the reinstall of the pip/setuptools/wheel call please?

**How to reproduce**
Run:
`pipx install <whatever_package> --index-url <host_of_artifact_url>`

**Expected behavior**
Should see that it uses the passed in `--index-url`:
`python -m pip --disable-pip-version-check install --index-url <host_of_artifact_url> --force-reinstall --upgrade pip setuptools wheel`

**Comment by chrysle** [comment]
I'lll work on this.

**Comment by Arpafaucon** [comment]
Reopening this, it seems to me the problem still occurs with `pipx==1.4.3`

my working environment is a virtualenv + private artifactory. I noticed it by overriding the certificates, and noticed that pipx was querying pypi under the hood

```
DEBUG:root:Running ['/install/bin/python', '-m', 'pipx', 'install', '--verbose', '--python', '/install/bin/python', '--index-url', https://[PRIVATE_REPO_URL]/repository/Wandercraft/simple', 'conan', '--pip-args', '--index-url https://[PRIVATE_REPO_URL]/repository/Wandercraft/simple --constraint /src/wdc_build/python/requirements/isolated_reqs_conan.txt']
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is '/install/bin/python'
pipx >(mkdir:74): creating directory /install/pipx/venvs
pipx >(mkdir:74): creating directory /home/builder/.local/share/man
pipx >(mkdir:74): creating directory /install/pipx/.cache
pipx >(package_name_from_spec:370): Determined package name: conan
pipx >(package_name_from_spec:371): Package name determined in 0.0s
creating virtual environment...
pipx >(run_subprocess:168): running /install/bin/python -m venv --without-pip /install/pipx/venvs/conan
creating shared libraries...
pipx >(run_subprocess:168): running /install/bin/python -m venv --clear /install/pipx/shared
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(upgrade:98): Upgrading shared libraries in /install/pipx/shared
upgrading shared libraries...
pipx >(run_subprocess:168): running /install/pipx/shared/bin/python -m pip --no-input --disable-pip-version-check install --force-reinstall --upgrade pip >= 23.1
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /simple/pip/
ERROR: Could not find a version that satisfies the requirement pip>=23.1 (from versions: none)
ERROR: No matching distribution found for pip>=23.1
pipx >(upgrade:125): Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/install/lib/python3.10/site-packages/pipx/shared_libs.py", line 119, in upgrade
    subprocess_post_check(upgrade_process)
  File "/install/lib/python3.10/site-packages/pipx/util.py", line 205, in subprocess_post_check
    raise PipxError(f"{' '.join([str(x) for x in completed_process.args])!r} failed")
pipx.util.PipxError: '/install/pipx/shared/bin/python -m pip --no-input --disable-pip-version-check install --force-reinstall --upgrade pip >= 23.1' failed
```

**Comment by Arpafaucon** [comment]
I'll have a go at this, thanks for the pointer

**Comment by Arpafaucon** [comment]
ping @chrysle on #1256 , it seems to me that a dedicated method would be more appropriate to clarify the shared lib behavior. I'll be glad to have your opinion on this
